version: '3.7'

services:
  db:
    image: postgres
    container_name: app_database
    command: -p 5433
    expose:
      - 5433
    environment:
      - POSTGRES_DB=testDb
      - POSTGRES_PASSWORD=pass
    
  app:
    build: 
      context: .
    container_name: app_name
    env_file:
      - .dev_env
    depends_on:
      - db


